### ISSUE TITLE
Compatible image not specified

### ISSUE THREAD

**Issue by pjgoodall** [jmari/JupyterTalk#1]
Hi,

I configure a n image and VM using `wget https://get.pharo.org/64/stable+vmT | bash`
When I try to run the install script in a playground:

```
Metacello new 
	baseline: 'JupyterTalk';
	repository: 'github://jmari/JupyterTalk:master/repository';
	load:'all'
```
I get:
```
This package depends on the following classes:
  RTObject
  RTBuilder
  RTTabTable
  RTVisitor
  RTView
```
Using Dr Google I get [reference to Roussal](http://agilevisualization.com/AgileVisualization/QuickStart/0101-QuickStart.html), which makes some sense.
I'd like some guidance in your beautifully-presented document (thank-you), as to which configuration of Pharo to start from.
Cheers...

**Comment by jmari** [comment]
Yes, if you try to load "All", it will install helper classes to work with Roassal. If I am not wrong it works with any Roassal 2 version. If Roassal is not installed you can ignore the warnings...It's not so elegant, I think the best way could be ask the user for Roassal installation and execute this script (works for me):
   Gofer it 
            smalltalkhubUser: 'ObjectProfile' project: 'Roassal2'; 
            configurationOf: 'Roassal2'; 
            loadStable. 
But also there are some warnings in Roassal Installation process...
