### ISSUE TITLE
Can not use copy options in the tutorial

### ISSUE THREAD

**Issue by akevalion** [jmari/JupyterTalk#3]
Hi I tried to use the tutorial but I can not select text from the examples and code snippets, can you please remove the limitations in order to copy and execute code in pharo

http://htmlpreview.github.io/?https://github.com/jmari/JupyterTalk/blob/master/Tutorial1_BasicStatistics.html

**Comment by jmari** [comment]
yes but I this is a rendering limitation from github...any suggestion?

**Comment by jmari** [comment]
only happens in the first one...strange

**Comment by jmari** [comment]
Since many time, you can open /master/notebooks/Tutorial1_BasicStatistics.ipynb file instead and copy/paste

**Comment by akevalion** [comment]
I test it and it works ok now, thank you
