### ISSUE TITLE
License for the ZeroMQ binding

### ISSUE THREAD

**Issue by PierceNg** [jmari/JupyterTalk#4]
Is it under GPL 3 as with the rest of the repo? If so, can you consider licensing it under MIT as per panuw/zeromq?

**Comment by jmari** [comment]
Ok, zeromq binding is now under MIT license. I think the best will be colaborate with panuw/zeromq and join this fork to his repo now that he has created the repo in Github

**Comment by PierceNg** [comment]
Thank you. Yes it will be good to have a single source for the ZMQ binding for Pharo.

**Comment by tinchodias** [comment]
Hello! 
What is panuw/zeromq? Didn't find anything in https://github.com/panuw/zeromq

**Comment by jmari** [comment]
It is the original zeromq binding for Pharo, I made a "fork" and ported to uffi in this project. It was stored in http://smalltalkhub.com/#!/~panuw/zeromq

**Comment by jmari** [comment]
There is also a GitHub repo https://github.com/dellani/zeroMQ

**Comment by tinchodias** [comment]
Thank you very much!
