### ISSUE TITLE
Provide MyBinder Working Example

### ISSUE THREAD

**Issue by psychemedia** [jmari/JupyterTalk#5]
The README suggests that this kernel should work on an Ubuntu machine. It would be really useful if a MyBinder demo were provided so that the environment could be quickly evaluated.

If there is a simple script that can be used to install Pharo (presumably?), the zmq etc package and set up the kernel, that could all be placed in a `postBuild` file in the top level of the repo and MyBinder should pick it up and install everything required.

**Comment by jmari** [comment]
It's seems a very good idea, looks easy to deploy, zmq should be already installed because it is used by Jupyter, normally the problem is to be able to find it, same issue with the default installation folder for the kernel.json file... I'll try to do it.

**Comment by jmari** [comment]
No way ... I tried so hard but it does't work. 
I was able to download pharo into the docker image but it seems there was no internet connection and I could not download and install the project.
I tried a ready made image also, but when I wrote the kernel.json file I had no permissions to write

**Comment by jmari** [comment]
sorry I closed...my mistake

**Comment by jmari** [comment]
It is ready , at last the solution was to copy Pharo and pharo image in the repo.
I have to update the notebooks because all the used  frameworks have changed a lot...and organize the repo...

**Comment by psychemedia** [comment]
Wonderful - thanks for fixing that...
