### ISSUE TITLE
Does not work with docker

### ISSUE THREAD

**Issue by euberdeveloper** [jmari/JupyterTalk#6]
Hi, this is my Dockerfile:

```
FROM basmalltalk/pharo:9.0-image
USER root
# Update and upgrade apt
RUN apt update && apt upgrade -y
# Install Python 3.9.1
RUN apt install wget build-essential libreadline-gplv2-dev \
    libncursesw5-dev libssl-dev libsqlite3-dev tk-dev \
    libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev \
    -y
RUN wget https://www.python.org/ftp/python/3.9.1/Python-3.9.1.tgz && \
    tar xzf Python-3.9.1.tgz
RUN cd Python-3.9.1 && \
    ./configure --enable-optimizations && \
    make -j 2 && \
    make altinstall
# Install pip 21
RUN apt install python3-pip -y
RUN pip3 install --upgrade pip
# Install jupyter notebooks
RUN pip install jupyter
# Install IPharo
RUN ./pharo Pharo.image eval --save "Metacello new \
    baseline:'IPharo'; \
    repository: 'github://jmari/IPharo:master/repository'; \
    load: 'default'"
RUN jupyter notebook
```

But it stops in the Metacello step, with:

```
Instance of BaselineOfPharo class did not understand #specRepository
BaselineOfPharo class(Object)>>doesNotUnderstand: #specRepository
[ :aClass | aClass specRepository ] in BaselineOfSpec2>>defaultRepositoryURL in Block: [ :aClass | aClass specRepository ]
FullBlockClosure(BlockClosure)>>cull:
[:v | ^ aPresentBlock cull: v] in SystemDictionary(Dictionary)>>at:ifPresent:ifAbsent: in Block: [:v | ^ aPresentBlock cull: v]
FullBlockClosure(BlockClosure)>>cull:
SystemDictionary(Dictionary)>>at:ifPresent:
SystemDictionary(Dictionary)>>at:ifPresent:ifAbsent:
BaselineOfSpec2>>defaultRepositoryURL
[ self defaultRepositoryURL ] in [ 
                spec 
                        repository: (self packageRepositoryURL ifEmpty: [ self defaultRepositoryURL ]);
                        loads: #('Base' 'Tests') ] in BaselineOfSpec2>>specCore: in Block: [ self defaultRepositoryURL ]
ByteString(Collection)>>ifEmpty:
[ 
                spec 
                        repository: (self packageRepositoryURL ifEmpty: [ self defaultRepositoryURL ]);
                        loads: #('Base' 'Tests') ] in BaselineOfSpec2>>specCore: in Block: [ ...
FullBlockClosure(BlockClosure)>>ensure:
MetacelloBaselineConstructor(MetacelloAbstractVersionConstructor)>>with:during:
MetacelloBaselineConstructor(MetacelloAbstractVersionConstructor)>>setBaseline:withBlock:
FullBlockClosure(BlockClosure)>>setBaseline:withInMetacelloConfig:
MetacelloBaselineConstructor(MetacelloAbstractVersionConstructor)>>baselineForVersion:with:
MetacelloMCVersionSpec(MetacelloVersionSpec)>>baseline:with:constructor:
MetacelloBaselineConstructor(MetacelloAbstractVersionConstructor)>>baseline:with:
BaselineOfSpec2>>specCore:
[

                self specCore: spec.
                self specCoreCode: spec.

                spec
                        "Core"
                        package: 'Spec2-Adapters-Morphic' with: [ spec requires: #('SpecCore') ];
                        package: 'Spec2-Code-Morphic' with: [ spec requires: #('Spec2-Adapters-Morphic') ];
                        package: 'Spec2-Code-Diff-Morphic' with: [ spec requires: #('Spec2-Adapters-Morphic') ];
                        package: 'Spec2-Morphic' with: [ spec requires: #('Spec2-Adapters-Morphic') ];
                        "Tests"
                        package: 'Spec2-Morphic-Examples' with: [ spec requires: #('Spec2-Morphic') ];
                        package: 'Spec2-Backend-Tests' with: [ spec requires: #('SpecCore' 'Spec2-Adapters-Morphic') ];
                        package: 'Spec2-Morphic-Backend-Tests' with: [ spec requires: #('Spec2-Adapters-Morphic' 'Spec2-Backend-Tests') ];
                        package: 'Spec2-Adapters-Morphic-Tests' with: [ spec requires: #('Spec2-Backend-Tests') ];
                        package: 'Spec2-Morphic-Tests' with: [ spec requires: #('Spec2-Morphic' 'Spec2-Backend-Tests') ];
                        package: 'Spec2-Code-Backend-Tests' with: [ spec requires: #('Spec2-Backend-Tests') ];
                        "others"
                        package: 'Spec2-Deprecated10' with: [ spec requires: #('SpecCore' 'Spec2-Morphic' 'Spec2-Morphic-Tests' 'Spec2-Backend-Tests' 'Spec2-Adapters-Morphic') ];
                        package: 'Spec2-Microdown' with: [ spec requires: #('SpecCore' 'Spec2-Adapters-Morphic') ];
                        package: 'Spec2-Help';
                        package: 'Spec2-Transformations' ] in BaselineOfSpec2>>baseline: in Block: [...
FullBlockClosure(BlockClosure)>>ensure:
MetacelloBaselineConstructor(MetacelloAbstractVersionConstructor)>>with:during:
[ :block | self with: versionSpec during: block ] in [ :attribute | 
            | blockList |
            (blockList := self attributeMap at: attribute ifAbsent: [  ]) ~~ nil
                ifTrue: [ blockList do: [ :block | self with: versionSpec during: block ] ] ] in MetacelloBaselineConstructor>>calculate:project: in Block: [ :block | self with: versionSpec during: block ]
OrderedCollection>>do:
[ :attribute | 
            | blockList |
            (blockList := self attributeMap at: attribute ifAbsent: [  ]) ~~ nil
                ifTrue: [ blockList do: [ :block | self with: versionSpec during: block ] ] ] in MetacelloBaselineConstructor>>calculate:project: in Block: [ :attribute | ...
OrderedCollection>>do:
MetacelloBaselineConstructor>>calculate:project:
MetacelloBaselineConstructor>>on:project:
MetacelloBaselineConstructor class>>on:project:
BaselineOfSpec2(ConfigurationOf)>>project
0mThe command '/bin/sh -c ./pharo Pharo.image eval --save "Metacello new     baseline:'IPharo';     repository: 'github://jmari/IPharo:master/repository';     load: 'default'"' returned a non-zero code: 1
```

**Comment by jmari** [comment]
I'll take a look, I was working on IPharo a couple of months ago doing many changes in order to support jupyter debugging protocol and may be there are some unfinished work. Anyway probably this error is caused because the  installation asks for install ing Roassal using UIManager so it won't work on the command line.

**Comment by jmari** [comment]
seems there is a problem with a DAPServer dependency on Spec2 I will remove DAP dependency from the default group. Do you need debugging support? If I'm not wrong it is not widely supported

**Comment by euberdeveloper** [comment]
Yes, maybe it is not supported on the system of the Docker file. But I also have tried locally and there was an error about the fact that the parent directory of the Pharo kernel did not exist (even if it did)

**Comment by jmari** [comment]
please check again installing #default group. It won't load PharoDAP and debugger support. About write permissions the installation script tries to create the config file for Pharo kernel at the paths returned by "jupyter kernelspec list"...I know nothing about docker but it could be a reason for your error.
Maybe you should create your own kernel.json this is the default file content generated by the baseline. Please let me know if it already works for you.
	
	^ '{
  "argv": [
  "', FileLocator vmBinary fullName,'",
  "--headless", "', FileLocator image fullName, '",
  "ipharo",
  "{connection_file}"
	],
	"display_name": "Pharo Smalltalk",
	"language": "smalltalk",
	"metadata": { "debugger": true }
	}'


createKernelFile
	| listOfKernels first last  kernelPath kernelsDir fileRef outString stream |
	
	outString := LibC resultOfCommand: 'jupyter kernelspec list'.
	listOfKernels := outString findTokens: Character lf.
	2 to:listOfKernels size do:[ :index |
		first := (listOfKernels at: index) findString: ' ' startingAt: 12.
		last := (listOfKernels at: index) findString: 'kernels'.
		kernelPath := (listOfKernels at:index) copyFrom: first +2 to: last + 7.
		kernelsDir := (FileSystem root / kernelPath / 'pharo') createDirectory.  
		fileRef := kernelsDir / 'kernel.json'.  
		[ fileRef := fileRef ensureCreateFile.
		stream := fileRef writeStream.
		stream nextPutAll: self kernelFileContents.
		stream close ] 
	on:Error 
	do:[ Transcript crShow:('Pharo Could not create the file ',fileRef,' not enough permissions' ) ] ]

**Comment by jmari** [comment]
I've been able to install IPĥaro and  run jupyter with the following script.  I had to install nano and edit /usr/local/share/jupyter/kernels/pharo/kernel.json and change the command line to /opt/pharo/pharo and remove the --headless option because (Filelocator vmBinary gives me the correct path the installed version can not be runnig in that way...) 

Sooo.... I have to make an special Metacello installation script for docker but it will run!
```
FROM basmalltalk/pharo:9.0-image
USER root
# Update and upgrade apt
RUN apt update && apt upgrade -y
# Install Python 3.9.1
RUN apt install wget build-essential libreadline-gplv2-dev \
    libncursesw5-dev libssl-dev libsqlite3-dev tk-dev \
    libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev \
    -y
RUN wget https://www.python.org/ftp/python/3.9.1/Python-3.9.1.tgz && \
    tar xzf Python-3.9.1.tgz
RUN cd Python-3.9.1 && \
    ./configure --enable-optimizations && \
    make -j 2 && \
    make altinstall
# Install pip 21
RUN apt install python3-pip -y
RUN pip3 install --upgrade pip
# Install jupyter notebooks
RUN pip install jupyter
#install ZMQ

WORKDIR /opt/
RUN apt-get install -y libtool
RUN wget https://github.com/zeromq/zeromq4-1/releases/download/v4.1.5/zeromq-4.1.5.tar.gz
RUN tar -xzf zeromq-4.1.5.tar.gz
WORKDIR /opt/zeromq-4.1.5
RUN ./autogen.sh
RUN ./configure
RUN make
#RUN make check
RUN make install


WORKDIR /opt/pharo
# Install IPharo

RUN ./pharo Pharo.image eval --save "Metacello new \
    baseline:'IPharo'; \
    repository: 'github://jmari/IPharo:master/repository'; \
    load: 'default'"

RUN jupyter notebook --port=9999 --no-browser --ip=0.0.0.0 --allow-root

```

**Comment by jmari** [comment]
### it works!
Please check it and tell me if it works for your system

**Comment by euberdeveloper** [comment]
Very good, it works!!!

I think that a good idea could be to publish a public image on Dockerhub

**Comment by jmari** [comment]
Yes, me too, and is a good opportunity to learn a little about docker. I want to include roassal but by now, only roassal 2 is supported and I want to upgrade to roassal 3 before...step by step ;-)

**Comment by euberdeveloper** [comment]
A good improvement could be using env files to specify configurations (such as port of jupyter, password of jupyter, Pharo version, ...). An idea is specifying a folder with .env where the user will put a physical volume and out the .ipynb files that will be shared between the container and the real  os.

You could use also a multistage dockerfile, to automatically remove thongs that are not needed in the final image, but I don't think is the case here.

Another thing is that every time you execute "RUN" a new image is created taking the previous steps as base. So if you change only one run, all the part before is not executed again. It's a good practice not to put al lot of RUN because it becomes overkill and consumes memory, it's better to execute things related to each other in a single RUN with && and \ for newline.

**Comment by jmari** [comment]
close the issue but I do not forget the idea

**Comment by euberdeveloper** [comment]
@jmari 

Eventually I published a Docker image on my account, you can check it [here](https://github.com/euberdeveloper/docker-ipharo) and [here](https://hub.docker.com/repository/docker/euberdeveloper/ipharo).

It seems working well, it also supports jupyters's arguments as passed env vars.

The only thing is that the image is HUGE, it reaches almost 2GB, would you have any idea about how to reduce it?
